version: '3'

services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: fusionauth
      MYSQL_USER: fusionauth
      MYSQL_PASSWORD: fusionauth
      MYSQL_ROOT_PASSWORD: rootpassword
    healthcheck:
      test: mysql -u"$${MYSQL_USER}" -p"$${MYSQL_PASSWORD}" -hdb "$${MYSQL_DATABASE}" -e 'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES LIMIT 1;'
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - 3306:3306
    networks:
      - db_net

  fusionauth:
    image: fusionauth/fusionauth-app-mysql:latest
    build:
      context: .
      dockerfile: ./fusionauth.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/fusionauth?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&useUnicode=true&characterEncoding=UTF-8
      DATABASE_ROOT_USER: root
      DATABASE_ROOT_PASSWORD: rootpassword
      DATABASE_USERNAME: fusionauth
      DATABASE_PASSWORD: fusionauth
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database

    networks:
      - db_net
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config

networks:
  db_net:
    driver: bridge

volumes:
  fusionauth_config:
