version: '3'

services:
  db:
    image: tiksn-fusionauth:latest
    build:
      context: ./tiksn-fusionauth
      dockerfile: ./tiksn-fusionauth.Dockerfile
    environment:
      MYSQL_DATABASE: fusionauth
      MYSQL_USER: fusionauth
      MYSQL_PASSWORD: fusionauth
    healthcheck:
      test: dolt sql-client --host=db --port=3306 --user="$${MYSQL_USER}" --password="$${MYSQL_PASSWORD}" --use-db="$${MYSQL_DATABASE}" --query="SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES LIMIT 1;"
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - 3306:3306
    networks:
      - db_net
    volumes:
      - db_data:/dolthub-dbs

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: search
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    healthcheck:
      test: [ "CMD", "curl",  "--fail" ,"--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:9200/" ]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - search_net
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - search_data:/usr/share/elasticsearch/data

  fusionauth:
    image: fusionauth/fusionauth-app-mysql:latest
    build:
      context: ./fusionauth
      dockerfile: ./fusionauth.Dockerfile
    depends_on:
      db:
        condition: service_healthy
      search:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/fusionauth?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&useUnicode=true&characterEncoding=UTF-8
      DATABASE_ROOT_USER: fusionauth
      DATABASE_ROOT_PASSWORD: fusionauth
      DATABASE_USERNAME: fusionauth
      DATABASE_PASSWORD: fusionauth
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_SERVERS: http://search:9200
      SEARCH_TYPE: elasticsearch

    networks:
      - db_net
      - search_net
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config

networks:
  db_net:
    driver: bridge
  search_net:
    driver: bridge

volumes:
  db_data:
  fusionauth_config:
  search_data:
