services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: fusionauth
      MYSQL_USER: fusionauth
      MYSQL_PASSWORD: fusionauth
      MYSQL_ROOT_PASSWORD: rootpassword
    healthcheck:
      test: mysql -u"$${MYSQL_USER}" -p"$${MYSQL_PASSWORD}" -hdb "$${MYSQL_DATABASE}" -e 'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES LIMIT 1;'
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - 3306:3306
    networks:
      - app_net
    restart: unless-stopped

  fusionauth:
    image: fusionauth/fusionauth-app-mysql:latest
    build:
      context: ./fusionauth
      dockerfile: ./fusionauth.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/fusionauth?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&useUnicode=true&characterEncoding=UTF-8
      DATABASE_ROOT_USERNAME: root
      DATABASE_ROOT_PASSWORD: rootpassword
      DATABASE_USERNAME: fusionauth
      DATABASE_PASSWORD: fusionauth
      FUSIONAUTH_APP_MEMORY: 512M
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database
      FUSIONAUTH_APP_KICKSTART_FILE: /usr/local/fusionauth/kickstart/kickstart.json
    healthcheck:
      test: curl --silent --fail http://localhost:9011/api/status -o /dev/null -w "%{http_code}"
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 9011:9011
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config
      - ./kickstart:/usr/local/fusionauth/kickstart
    networks:
      - app_net
    restart: unless-stopped

  ergo:
    image: tiksn/ergo:latest
    depends_on:
      fusionauth:
        condition: service_healthy
    environment:
      FUSIONAUTH_API_KEY: 047a124c-2dbc-4b68-84cc-55f9a204f4ea
      FUSIONAUTH_BASE_URL: http://fusionauth:9011/
    networks:
      - app_net

  api:
    image: tiksn/fossa-api:latest
    depends_on:
      fusionauth:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT}
      Identity__RootAddress: http://fusionauth:9011
      ConnectionStrings__MongoDB: ${ConnectionStrings__MongoDB}
      GeneratorId: ${GeneratorId}
    ports:
      - 20955:8080
    networks:
      - app_net
    restart: unless-stopped


networks:
  app_net:
    driver: bridge

volumes:
  fusionauth_config:
