services:
  fusionauth-db:
    image: postgres:16.0-bookworm
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: fusionauth
      POSTGRES_PASSWORD: fusionauth
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fusionauth_db_net
    restart: unless-stopped
    volumes:
      - fusionauth_db_data:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      fusionauth-db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://fusionauth-db:5432/fusionauth
      DATABASE_ROOT_USERNAME: fusionauth
      DATABASE_ROOT_PASSWORD: fusionauth
      DATABASE_USERNAME: fusionauth
      DATABASE_PASSWORD: fusionauth
      FUSIONAUTH_APP_MEMORY: 512M
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database
      FUSIONAUTH_APP_KICKSTART_FILE: /usr/local/fusionauth/kickstart/kickstart.json
    healthcheck:
      test: curl --silent --fail http://localhost:9011/api/status -o /dev/null -w "%{http_code}"
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 9011:9011
    networks:
      - fusionauth_db_net
      - idp_net
      - app_net
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config
      - ./kickstart:/usr/local/fusionauth/kickstart
    restart: unless-stopped

  ergo:
    image: tiksn/ergo:latest
    depends_on:
      fusionauth:
        condition: service_healthy
    environment:
      FUSIONAUTH_API_KEY: 047a124c-2dbc-4b68-84cc-55f9a204f4ea
      FUSIONAUTH_BASE_URL: http://fusionauth:9011/
    networks:
      - idp_net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    environment:
      DD_API_KEY: ${DD_API_KEY}
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - app_net
    restart: unless-stopped

  api:
    image: tiksn/fossa-api:latest
    depends_on:
      fusionauth:
        condition: service_healthy
      ergo:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT}
      Identity__RootAddress: http://fusionauth:9011
      Identity__ApiKey: 047a124c-2dbc-4b68-84cc-55f9a204f4ea
      ConnectionStrings__MongoDB: ${ConnectionStrings__MongoDB}
      GeneratorId: ${GeneratorId}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    ports:
      - 5210:8080
    networks:
      - app_net
    restart: unless-stopped

  ui:
    image: tiksn/fossa-ui:latest
    depends_on:
      api:
        condition: service_healthy
    ports:
      - 4210:3000
    networks:
      - app_net
    restart: unless-stopped

networks:
  fusionauth_db_net:
    driver: bridge
  idp_net:
    driver: bridge
  app_net:
    driver: bridge

volumes:
  fusionauth_db_data:
  fusionauth_config:
