receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  datadog:
    traces:
      span_name_as_resource_name: true
      trace_buffer: 500
    metrics:
    logs:
    hostname: "otelcol-docker"
    api:
      key: ${DD_API_KEY}
      site: us5.datadoghq.com
  otlphttp/honeycomb:
    endpoint: "https://api.honeycomb.io"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "${HONEYCOMB_DATASET}"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [datadog, otlphttp/honeycomb]
    traces:
      receivers: [otlp]
      exporters: [datadog, otlphttp/honeycomb]
    logs:
      receivers: [otlp]
      exporters: [datadog, otlphttp/honeycomb]