receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  datadog:
    traces:
      span_name_as_resource_name: true
      trace_buffer: 500
    metrics:
    logs:
    hostname: "otelcol-docker"
    api:
      key: ${DD_API_KEY}
      site: us5.datadoghq.com
  otlphttp/honeycomb:
    endpoint: "https://api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "${HONEYCOMB_DATASET}"
  otlphttp/sentry:
    logs_endpoint: https://o4510282140680192.ingest.us.sentry.io/api/4510282155622400/integration/otlp/v1/logs
    traces_endpoint: https://o4510282140680192.ingest.us.sentry.io/api/4510282155622400/integration/otlp/v1/traces
    headers:
      x-sentry-auth: "sentry sentry_key=${SENTRY_KEY}"
    compression: gzip
    encoding: proto
    timeout: 30s

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [datadog, otlphttp/honeycomb]
    traces:
      receivers: [otlp]
      exporters: [datadog, otlphttp/honeycomb, otlphttp/sentry]
    logs:
      receivers: [otlp]
      exporters: [datadog, otlphttp/honeycomb, otlphttp/sentry]