# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
# define global settings here
# name: exampleapp # application name
# registry: exampleuser # dockerhub username or container registry hostname

# define multiple services here
services:
- name: identity
  image: fusionauth/fusionauth-app:latest
  env:
    - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/fusionauth
    - FUSIONAUTH_APP_RUNTIME_MODE=development
    - FUSIONAUTH_APP_URL=http://fusionauth:9011
    - SEARCH_TYPE=database
  env_file:
    - ./.env
  bindings:
    - port: 9011
- name: identity-database
  image: postgres:alpine
  env_file:
    - ./.env
  bindings:
    - port: 5432

